services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=verysecret
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8000:80" # open http://localhost:8080 in your browser
    environment:
      - PMA_HOST=mysql
      - PMA_USER=myuser
      - PMA_PASSWORD=secret
    depends_on:
      - mysql

volumes:
  my-db: {}
