services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"  # Expose port 3306 for localhost
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=verysecret
    volumes:
      - my-db:/var/lib/mysql # to persist
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  my-db: {}
