spring:
    config:
        activate:
            on-profile: test
    datasource: 
        url: jdbc:h2:mem:testdb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    sql:
        init:
            mode: never